services:
  app:
    build: .
    container_name: webhook
    restart: unless-stopped
    depends_on:
      - nats
    env_file:
      - .env
    ports:
      - "8001:8001"

  nats:
    image: nats:latest
    container_name: nats
    restart: unless-stopped
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    depends_on:
      - app
    env_file:
      - .env
    command:
      - tunnel
      - --url
      - http://app:8001
      - --protocol
      - http2
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARED_TUNNEL_TOKEN}
    restart: unless-stopped
